name: Generate Snake Animation

on:
  schedule:
    # Run at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: Nabilislam722
          outputs: svg
      - name: Commit Snake Animation
        run: |
          git config --global user.name "Nabil Islam"
          git config --global user.email "youremail@example.com"
          git add -A
          git commit -m "Updated snake animation"
          git push
